Repository Activiti/activiti-cloud-dependencies, pull requests merged in 2018-11, with the labels that each got.

#179 update org.activiti.cloud.app:activiti-cloud-app-dependencies to 7.0.25
  pom.xml
Labels: updatebot

#180 update org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies to 7.0.42
  pom.xml
Labels: updatebot

#190 update org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies to 7.0.2
  pom.xml
Labels: in progress, updatebot

#194 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  dependencies-tests/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#191 update org.activiti.cloud.api:activiti-cloud-api-dependencies to 7.0.28
  pom.xml
Labels: in progress, updatebot

#206 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#208 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#207 Add dependency convergence tests for Cloud Dependencies
  .mergify.yml
  .updatebot.yml
  dependencies-tests/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#209 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#210 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#211 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#212 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Jenkinsfile
  pom.xml
Labels: in progress, updatebot

#214 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#215 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot

#216 fix(versions): update Activiti/activiti-cloud-dependencies versions
  pom.xml
Labels: in progress, updatebot
