Repository Activiti/activiti-cloud-dependencies, pull requests merged in 2019-11, with the labels that each got.

#484 fix(versions): update Activiti/activiti-cloud-dependencies versions into develop
  pom.xml
Labels: updatebot

#473 feat: added example-runtime-bundle test dependency
  .updatebot.yml
  Jenkinsfile
  Makefile
  dependencies-tests/pom.xml
Labels: enhancement

#485 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#486 fix(versions): update Activiti/activiti-cloud-dependencies versions
  .updatebot.yml
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#488 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Jenkinsfile
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#492 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: do-not-merge, updatebot

#493 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#494 fix(versions): update Activiti/activiti-cloud-dependencies versions into develop
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#495 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#496 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#498 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#499 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#500 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#501 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#502 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#503 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#506 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
Labels: updatebot

#507 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#508 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#509 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#510 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#511 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#513 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#514 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#515 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#516 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#517 fix(versions): update Activiti/activiti-cloud-dependencies versions into develop
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#518 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#519 fix(versions): update Activiti/activiti-cloud-dependencies versions into develop
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#520 fix(versions): update Activiti/activiti-cloud-dependencies versions into develop
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#521 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#524 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#525 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#526 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#527 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#528 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot

#529 fix(versions): update Activiti/activiti-cloud-dependencies versions into develop
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#530 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#531 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
  dependencies-tests/pom.xml
  pom.xml
Labels: updatebot

#532 fix(versions): update Activiti/activiti-cloud-dependencies versions
  Makefile
Labels: updatebot
